name: my second workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: welcome message
          run: echo "my first github action"

        - name: lsit files
          run: ls -l
          
        - name: read file
          run: cat README.md
