name: my second workflow

on: push

jobs: 
    first_job:
        runs-on: ubuntu-latest
        steps:
        - name: checkout repo
          uses: actions/checkout@v4

        - name: list and read files
          run: |
            echo "my first github action"
            ls
            cat README.mc

        - name: Generate ASCII Artwork
          run: cosway -f dragon "blah blah Dragon" >> dragon.txt
